export let cartelera=[
    {
        nombre:"PANTERA NEGRA: WAKANDA POR SIEMPRE",
        genero:"Drama, ACCION",
        duracion:"110 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2FWakanda.jpg?alt=media&token=0d920d37-cba0-482e-8b16-92e8546aa5ab",
        sinopsis:"En PANTERA NEGRA: WAKANDA POR SIEMPRE de Marvel Studios, la reina Ramonda (Angela Bassett), Shuri (Letitia Wright), M'Baku (Winston Duke), Okoye (Danai Gurira) y las Dora Milaje (incluida Florence Kasumba) luchan por proteger a su nación de las potencias mundiales que intervienen tras la muerte del Rey T'Challa. Mientras los habitantes de Wakanda se esfuerzan por embarcarse en un nuevo capítulo, los héroes deben unirse con la ayuda de War Dog Nakia (Lupita Nyong'o) y Everett Ross (Martin Freeman) y forjar un nuevo camino para el reino de Wakanda. El film que cuenta con Tenoch Huerta como Namor, rey de una nación submarina oculta, también está protagonizada por Dominique Thorne, Michaela Coel, Mabel Cadena y Alex Livanalli.",
        idioma:"ESPAÑOL",
        director:"HARRY KANE",
        actor:"ADRIAN RAMOS, QUIÑONES, NEYMAR",
        
    },
    {
        
        nombre:"LA LUZ DEL DIABLO",
        genero:"TERROR, Suspenso",
        duracion:"90 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2F060c5a67e861-480x670.png?alt=media&token=60904620-aceb-4047-b73d-1cca74a23b59",
        sinopsis:"Según informes reales del Vaticano, los casos de posesión demoníaca han aumentado significativamente en los últimos años. En respuesta, la iglesia católica ha reabierto en secreto escuelas de exorcismo para capacitar a los sacerdotes en este rito sagrado. LA LUZ DEL DIABLO te sumerge en el mundo de una de estas escuelas; última línea de defensa de la humanidad contra los poderes del mal. La hermana Ann, cree devotamente que realizar exorcismos es su vocación, a pesar de que históricamente sólo los sacerdotes, y no las hermanas, pueden realizarlos. Cuando un profesor siente su don especial, decide aceptarla en el aula, le permite ser la primera monja en estudiar y dominar el ritual. Su propia alma estará en peligro ya que las fuerzas demoníacas con las que lucha revelarán una conexión misteriosa con su pasado traumático.",
        idioma:"Español",
        director:"CRISTIAN LEMOS SALAS",
        actor:"DANIEL CALDERON, MESSI, ALEXIA",
    },
    {
        nombre:"HASTA LOS HUESOS",
        genero:"AMOR",
        duracion:"95 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2FHasta%20los%20huesos.png?alt=media&token=e70cc6c7-a4e6-4e7b-88bb-b32fb94531a3",
        sinopsis:"",
        idioma:"Español",
        director:"MAGUIRE",
        actor:"RICHARLISON, LINIBETH, ALEXIA",
    },
    {
        nombre:"LA GRAN TORMENTA",
        genero:"SUSPENSO",
        duracion:"98 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2FLa%20gran%20tormenta.jpg?alt=media&token=245c4061-3beb-412c-91ca-fae59e25bac1",
        sinopsis:"Cuando su avión se estrella en una remota montaña cubierta de nieve, Jane y Paul tienen que luchar por sus vidas como los únicos sobrevivientes que quedan. Juntos se embarcan en un angustioso viaje fuera del desierto.",
        idioma:"Español",
        director:"WILLIAM MERCADO",
        actor:"LINIBETH, GISELA, JULIAN, BEKER",
    },
    {
        nombre:"BLACK ADAM",
        genero:"ACCION",
        duracion:"120 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2Fblack-Adam.png?alt=media&token=f56c1b89-bcea-4d26-8562-a555f0e177be",
        sinopsis:"Casi 5.000 años después de haber sido dotado de los poderes omnipotentes de los antiguos dioses -y encarcelado con la misma rapidez-, Black Adam (Johnson) es liberado de su tumba terrenal, listo para desatar su forma única de justicia en el mundo moderno.",
        idioma:"ESPAÑOL",
        director:"WILLIAM MERCADO",
        actor:"RUIZ, GOMEZ, JUAN",
    },
    {
        nombre:"LA JURIA",
        genero:"DRAMA, Comedia",
        duracion:"92 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2FLa%20juria.png?alt=media&token=d572dc4d-f8d6-43a5-be96-0f20ec258ff3",
        sinopsis:"En un centro de rehabilitación experimental en medio de la selva, Eliú paga una sentencia por asesinato. Cuando su mejor amigo y cómplice es trasladado al mismo lugar, los jóvenes deberán reconstruir su crimen y enfrentar un pasado del que Eliú se quiere alejar. En medio de terapias y trabajos forzados, Eliú se enfrentará a la oscuridad de la naturaleza humana y tratará de escapar de la suya antes de que sea demasiado tarde",
        idioma:"Español",
        director:"XAVI HERNANDEZ",
        actor:"ALEX, MATURANA, VALDERRAMA",
    },
    {
        nombre:"LA ROYA",
        genero:"DRAMA",
        duracion:"98 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2FLa-Troya.jpg?alt=media&token=b78f0d92-5202-4c9d-8a0e-283d12ca6063",
        sinopsis:"Jorge es un joven campesino quien vive en lo alto de una montaña. Todos los de su generación han emigrado a la ciudad, pero él se ha quedado para hacerse cargo de la finca cafetera que ha heredado de su padre, mientras cuida de su abuelo y tiene amoríos con su prima Rosa. Las festividades del pueblo se acercan y él espera con ansias el momento para reencontrarse con Andrea, su exnovia, a quien no ha podido olvidar a pesar del tiempo y la distancia. El deseo de volver a verla se convierte en obsesión, mientras una plaga silenciosa invade los cafetales. Llegan las fiestas y en medio de la música estridente y las alucinaciones Jorge comprenderá que todo lo que los unía ha desaparecido y que permanecer en su tierra es un acto de amor y resistencia",
        idioma:"ESPAÑOL",
        director:"JUAN GUILLERMO CUADRADO",
        actor:"VINICIUS, PAQUETA, MEDEL",
    },
    {
        nombre:"LOS REYES DEL MUNDO",
        genero:"AVENTURA Y DRAMA",
        duracion:"96 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2FLos%20reyes%20del%20mundo.jpg?alt=media&token=3cc0f359-0e52-47d1-bd77-f20e11d28b99",
        sinopsis:"Un día todos los hombres se quedaron dormidos… Y los cercos de la tierra, ardieron” Rá (19), Culebro (16), Sere (14), Winny (12) Nano (13) cinco chicos de la calle de Medellín. Cinco reyes sin reino. En sus manos tienen unas viejas escrituras de una tierra heredada por Rá. Tras recibir una carta de la oficina de restitución de tierras del gobierno, notificando la devolución de los terrenos que le fueron arrebatados a su abuela, Rá decidirá emprender el viaje con sus amigos con la promesa de por fin cumplir un sueño: tener un lugar en el mundo donde ser libres, donde estar a salvo, donde construir su propio reino.",
        idioma:"ESPAÑOL",
        director:"BUSTAMANTE",
        actor:"GREGORI, OSCAR, PASCUAL",
    },
    {
        nombre:"EL LLANTO DEL ANTICRISTO",
        genero:"TERROR, SUSPENSO, HORROR",
        duracion:"120 minutos",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinew-d1031.appspot.com/o/Cartelera%2FEl%20llanto%20del%20anticristo.png?alt=media&token=889f94d6-09fa-4ad3-983e-148b76710d9b",
        sinopsis:"Jacob Chandler es un hombre corriente con un don extraordinario y junto a su sobrino Liam han forjado una carrera exorcizando demonios de los cuerpos de sus clientes. Pero las cosas se están tornando cada día más oscuras, los días pasan y aumentan el número de poseídos por los espíritus del mal. De repente Jacob, es convocado a una casa de belleza inquietante con un pasado trágico donde debe recurrir a toda su experiencia para descubrir las capas de engaño demoniaco que están en juego. La muerte está aquí, y hará cualquier cosa para ser libre. Inspirado en hechos reales.",
        idioma:"ESPAÑOL",
        director:"WILLIAM MERCADO",
        actor:"RUIZ, GOMEZ, JUAN",
    },
]
